Authnchecks
atlassian-labs/connect-security-req-tester pull request #66
Opened 2023-07-14 18:18 UTC by sgandrathi

## Description of Change
* Adding Signed install check to existing authentication check.
* Updated authentication check to filter out results from post-install pages and invalid responses.
* Updated requirement variables and contacts to reflect the [latest security requirements](https://developer.atlassian.com/platform/marketplace/security-requirements/#connect-apps) numbering.
* Branding analysis is set to False from the default scan parameters.
* Added Cryptography library as a dependency for generating RSA private key.

## Fixes
* Security requirement variables and contacts are updated to reflect the [latest security requirements](https://developer.atlassian.com/platform/marketplace/security-requirements/#connect-apps) numbering.

## Did you test your changes?
- Yes

## Notes
- Added a call to the [MPAC](https://developer.atlassian.com/platform/marketplace/rest/v2/intro/#about) endpoint within a try/exception block.

## Reviewers
@jwong101 ,  @seanmarpo

2023-07-20 22:59 UTC, seanmarpo requested changes
Update `README.md` with documentation updates, otherwise, looks good to me

2023-07-20 22:59 UTC, seanmarpo commented on .github/workflows/csrt-lint-and-test.yml
> +#      run: |
Highly suggest we monitor https://github.com/nabla-c0d3/sslyze for releases so we can re-enable these checks. I have email alerts setup for new releases on that project.

2023-07-20 22:59 UTC, seanmarpo commented on main.py
> +def main(descriptor_url, skip_branding=True, debug=False, timeout=30, out_dir='out', json_logging=False):
Update the `README.md` with this new default value change

2023-07-21 02:39 UTC, sgandrathi commented on main.py
> +def main(descriptor_url, skip_branding=True, debug=False, timeout=30, out_dir='out', json_logging=False):
Updated ✅ , thanks for catching it.

2023-07-21 02:41 UTC, sgandrathi commented on .github/workflows/csrt-lint-and-test.yml
> +#      run: |
Sure, we will monitor and update it. I subscribed for the new releases on [Sslyze](https://github.com/nabla-c0d3/sslyze) project.

2023-07-21 05:36 UTC, seanmarpo approved these changes
👍 Looks good to me

2023-07-21 16:34 UTC, jwong101 approved these changes
LGTM

2023-08-10 15:14 UTC, merged